//
// Generated file, do not edit! Created by opp_msgtool 6.1 from nodes/mec/MECPlatform/MECServices/packets/AperiodicSubscriptionTimer.msg.
//

#ifndef __SIMU5G_APERIODICSUBSCRIPTIONTIMER_M_H
#define __SIMU5G_APERIODICSUBSCRIPTIONTIMER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class AperiodicSubscriptionTimer;

}  // namespace simu5g

// cplusplus {{
    #include <set>
// }}


namespace simu5g {

/**
 * Class generated from <tt>nodes/mec/MECPlatform/MECServices/packets/AperiodicSubscriptionTimer.msg:19</tt> by opp_msgtool.
 * <pre>
 * message AperiodicSubscriptionTimer
 * {
 *     double period;
 * }
 * </pre>
 */
class AperiodicSubscriptionTimer : public ::omnetpp::cMessage
{
  protected:
    double period = 0;

  private:
    void copy(const AperiodicSubscriptionTimer& other);

  protected:
    bool operator==(const AperiodicSubscriptionTimer&) = delete;

  public:
    AperiodicSubscriptionTimer(const char *name=nullptr, short kind=0);
    AperiodicSubscriptionTimer(const AperiodicSubscriptionTimer& other);
    virtual ~AperiodicSubscriptionTimer();
    AperiodicSubscriptionTimer& operator=(const AperiodicSubscriptionTimer& other);
    virtual AperiodicSubscriptionTimer *dup() const override {return new AperiodicSubscriptionTimer(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getPeriod() const;
    virtual void setPeriod(double period);


  private:
    std::set<int> subIdSet_;

  public:
    void insertSubId(int subId) { subIdSet_.insert(subId); }
    void removeSubId(int subId) { subIdSet_.erase(subId); }
    const std::set<int> getSubIdSet() const { return subIdSet_; }
    const int getSubIdSetSize() const { return subIdSet_.size(); }
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AperiodicSubscriptionTimer& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AperiodicSubscriptionTimer& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::AperiodicSubscriptionTimer *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::AperiodicSubscriptionTimer*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_APERIODICSUBSCRIPTIONTIMER_M_H

