//
// Generated file, do not edit! Created by opp_msgtool 6.1 from apps/mecRequestResponseApp/packets/MigrationTimer.msg.
//

#ifndef __SIMU5G_MIGRATIONTIMER_M_H
#define __SIMU5G_MIGRATIONTIMER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class MigrationTimer;

}  // namespace simu5g


namespace simu5g {

/**
 * Class generated from <tt>apps/mecRequestResponseApp/packets/MigrationTimer.msg:15</tt> by opp_msgtool.
 * <pre>
 * message MigrationTimer
 * {
 *     unsigned int oldAppId;
 *     unsigned int newAppId;
 * }
 * </pre>
 */
class MigrationTimer : public ::omnetpp::cMessage
{
  protected:
    unsigned int oldAppId = 0;
    unsigned int newAppId = 0;

  private:
    void copy(const MigrationTimer& other);

  protected:
    bool operator==(const MigrationTimer&) = delete;

  public:
    MigrationTimer(const char *name=nullptr, short kind=0);
    MigrationTimer(const MigrationTimer& other);
    virtual ~MigrationTimer();
    MigrationTimer& operator=(const MigrationTimer& other);
    virtual MigrationTimer *dup() const override {return new MigrationTimer(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getOldAppId() const;
    virtual void setOldAppId(unsigned int oldAppId);

    virtual unsigned int getNewAppId() const;
    virtual void setNewAppId(unsigned int newAppId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MigrationTimer& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MigrationTimer& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::MigrationTimer *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::MigrationTimer*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_MIGRATIONTIMER_M_H

