//
// Generated file, do not edit! Created by opp_msgtool 6.1 from common/timer/TTimerMsg.msg.
//

#ifndef __SIMU5G_TTIMERMSG_M_H
#define __SIMU5G_TTIMERMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class TTimerMsg;

}  // namespace simu5g

#include "common/LteCommon_m.h" // import common.LteCommon


namespace simu5g {

/**
 * Enum generated from <tt>common/timer/TTimerMsg.msg:16</tt> by opp_msgtool.
 * <pre>
 * enum TTimerType
 * {
 *     TTSIMPLE = 0;
 *     TTMULTI = 1;
 * }
 * </pre>
 */
enum TTimerType {
    TTSIMPLE = 0,
    TTMULTI = 1
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TTimerType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TTimerType& e) { int n; b->unpack(n); e = static_cast<TTimerType>(n); }

/**
 * Class generated from <tt>common/timer/TTimerMsg.msg:22</tt> by opp_msgtool.
 * <pre>
 * packet TTimerMsg
 * {
 *     unsigned int timerId;
 *     unsigned short type \@enum(TTimerType);
 * }
 * </pre>
 */
class TTimerMsg : public ::omnetpp::cPacket
{
  protected:
    unsigned int timerId = 0;
    unsigned short type = 0;

  private:
    void copy(const TTimerMsg& other);

  protected:
    bool operator==(const TTimerMsg&) = delete;

  public:
    TTimerMsg(const char *name=nullptr, short kind=0);
    TTimerMsg(const TTimerMsg& other);
    virtual ~TTimerMsg();
    TTimerMsg& operator=(const TTimerMsg& other);
    virtual TTimerMsg *dup() const override {return new TTimerMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getTimerId() const;
    virtual void setTimerId(unsigned int timerId);

    virtual unsigned short getType() const;
    virtual void setType(unsigned short type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TTimerMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TTimerMsg& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::TTimerMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::TTimerMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_TTIMERMSG_M_H

