//
// Generated file, do not edit! Created by opp_msgtool 6.1 from x2/packet/X2ControlInfo.msg.
//

#ifndef __SIMU5G_X2CONTROLINFO_M_H
#define __SIMU5G_X2CONTROLINFO_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class X2ControlInfoTag;

}  // namespace simu5g

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

#include "common/LteCommon_m.h" // import common.LteCommon

// cplusplus {{
    #include "common/LteCommon.h"

    namespace simu5g {
    typedef std::list<X2NodeId> DestinationIdList;
    }
// }}


namespace simu5g {

/**
 * Class generated from <tt>x2/packet/X2ControlInfo.msg:47</tt> by opp_msgtool.
 * <pre>
 * //
 * // \@class LteX2ControlInfo
 * //
 * // This class contains:
 * // - Source X2 ID
 * // - List of destination IDs
 * // - init flag
 * //
 * class X2ControlInfoTag extends inet::TagBase
 * {
 *     MacNodeId sourceId;                       // Source X2NodeId
 *     DestinationIdList destIdList;             // List of destination X2NodeId
 * 
 *     bool init = false;
 * }
 * </pre>
 */
class X2ControlInfoTag : public ::inet::TagBase
{
  protected:
    MacNodeId sourceId;
    DestinationIdList destIdList;
    bool init = false;

  private:
    void copy(const X2ControlInfoTag& other);

  protected:
    bool operator==(const X2ControlInfoTag&) = delete;

  public:
    X2ControlInfoTag();
    X2ControlInfoTag(const X2ControlInfoTag& other);
    virtual ~X2ControlInfoTag();
    X2ControlInfoTag& operator=(const X2ControlInfoTag& other);
    virtual X2ControlInfoTag *dup() const override {return new X2ControlInfoTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const MacNodeId& getSourceId() const;
    virtual MacNodeId& getSourceIdForUpdate() { return const_cast<MacNodeId&>(const_cast<X2ControlInfoTag*>(this)->getSourceId());}
    virtual void setSourceId(const MacNodeId& sourceId);

    virtual const DestinationIdList& getDestIdList() const;
    virtual DestinationIdList& getDestIdListForUpdate() { return const_cast<DestinationIdList&>(const_cast<X2ControlInfoTag*>(this)->getDestIdList());}
    virtual void setDestIdList(const DestinationIdList& destIdList);

    virtual bool getInit() const;
    virtual void setInit(bool init);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const X2ControlInfoTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, X2ControlInfoTag& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

inline any_ptr toAnyPtr(const simu5g::DestinationIdList *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline simu5g::DestinationIdList *fromAnyPtr(any_ptr ptr) { return ptr.get<simu5g::DestinationIdList>(); }
template<> inline simu5g::X2ControlInfoTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::X2ControlInfoTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_X2CONTROLINFO_M_H

