//
// Generated file, do not edit! Created by opp_msgtool 6.1 from apps/cbr/CbrPacket.msg.
//

#ifndef __SIMU5G_CBRPACKET_M_H
#define __SIMU5G_CBRPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class CbrPacket;

}  // namespace simu5g

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace simu5g {

/**
 * Class generated from <tt>apps/cbr/CbrPacket.msg:20</tt> by opp_msgtool.
 * <pre>
 * //
 * // Packet used by the ~VoPSender and ~VoIPReceiver modules.
 * //
 * class CbrPacket extends inet::FieldsChunk
 * {
 *     unsigned int nframes;
 *     unsigned int IDframe;
 *     simtime_t arrivalTime;
 *     simtime_t payloadTimestamp;
 *     unsigned int payloadSize;
 * }
 * </pre>
 */
class CbrPacket : public ::inet::FieldsChunk
{
  protected:
    unsigned int nframes = 0;
    unsigned int IDframe = 0;
    ::omnetpp::simtime_t arrivalTime = SIMTIME_ZERO;
    ::omnetpp::simtime_t payloadTimestamp = SIMTIME_ZERO;
    unsigned int payloadSize = 0;

  private:
    void copy(const CbrPacket& other);

  protected:
    bool operator==(const CbrPacket&) = delete;

  public:
    CbrPacket();
    CbrPacket(const CbrPacket& other);
    virtual ~CbrPacket();
    CbrPacket& operator=(const CbrPacket& other);
    virtual CbrPacket *dup() const override {return new CbrPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getNframes() const;
    virtual void setNframes(unsigned int nframes);

    virtual unsigned int getIDframe() const;
    virtual void setIDframe(unsigned int IDframe);

    virtual ::omnetpp::simtime_t getArrivalTime() const;
    virtual void setArrivalTime(::omnetpp::simtime_t arrivalTime);

    virtual ::omnetpp::simtime_t getPayloadTimestamp() const;
    virtual void setPayloadTimestamp(::omnetpp::simtime_t payloadTimestamp);

    virtual unsigned int getPayloadSize() const;
    virtual void setPayloadSize(unsigned int payloadSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CbrPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CbrPacket& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::CbrPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::CbrPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_CBRPACKET_M_H

